# region DEFAULTS
DEFAULT_ZIP_EXTRACT_OUTPUT_DIR = 'output'
DEFAULT_SUBMISSION_FILE_NAME_SEPARATOR = '_'
DEFAULT_FSCK_ERROR_LOG_FILE = 'fsck_err.log'
# endregion

# region INDEX
FILE_STUDENT_NAME_INDEX = 0
# endregion
