import os


# region DEFAULTS
DEFAULT_ZIP_EXTRACT_OUTPUT_DIR = '/tmp/auto_grader_output'
DEFAULT_SUBMISSION_FILE_NAME_SEPARATOR = '_'
DEFAULT_FSCK_ERROR_LOG_FILE = 'fsck_err.log'
DEFAULT_VALIDATION_OUTPUT_FILE = 'student_validation.csv'
# endregion

# region INDEX
FILE_STUDENT_NAME_INDEX = 0
# endregion

BASE_DIR = os.getcwd()
STUDENT_NAME_EXCLUDE_CHARS = ['.', ',', '-', ' ']
OUTPUT_COLUMNS = ['STUDENT ID', 'STUDENT_NAME', 'GIT INIT', 'GIT IS COMMITTED', 'GIT FSCK', 'GIT COMMITS']
